version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 14
    commands:
      - npm install -g fsh-sushi
      - gem install jekyll bundler
  pre_build:
    commands:
      - curl -OL https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar
      - git clone https://github.com/HealthDataWorks/fhir-ig-template-base.git custom-template
  build:
    commands:
      - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
      - ls
      - ls input-cache
      - ./_genonce.sh
  post_build:
    commands:
      - echo Delete S3 Bucket object...
      - aws s3 rm s3://${S3_BUCKET_NAME} --recursive
artifacts:
  files:
    - '**/*'
  base-directory: output
